# Generated by Django 2.1 on 2018-08-19 20:25

from django.db import migrations, models

def default_row(apps, schema_editor):
    ParsedSMSData = apps.get_model("mainapp","ParsedSMSData")
    try:
        ParsedSMSData.objects.all()
    except ParsedSMSData.DoesNotExist:
        parsed_sms_data_row = ParsedSMSData()
        parsed_sms_data_row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_auto_20180819_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSMSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_count', models.IntegerField(blank=True, default=0, null=True)),
                ('max_id_parsed', models.IntegerField(blank=True, default=0, null=True)),
                ('parsed_success_count', models.IntegerField(blank=True, default=0, null=True)),
                ('parsed_failure_count', models.IntegerField(blank=True, default=0, null=True)),
                ('parsed_error_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RunPython(default_row),
    ]
